# Generated by Django 3.0.6 on 2020-11-12 20:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0117_auto_20200423_0737'),
        ('order', '0083_merge_20200421_0529'),
        ('bits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitsDigitalContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('content_type', models.CharField(choices=[('file', 'digital_product')], default='file', max_length=128)),
                ('content_file', models.FileField(blank=True, upload_to='bits_digital_content')),
                ('token', models.UUIDField(editable=False, unique=True)),
                ('line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bits_digital_content', to='order.OrderLine')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bits_digital_contents', to='product.ProductVariant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
